paths:
  /api/service:
    post:
      summary: Créer un nouveau service
      tags: [Services]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - nomservice
                - categorie
                - nomgroupe
              properties:
                nomservice:
                  type: string
                  example: "Plomberie"
                  description: "Nom du service"
                categorie:
                  type: string
                  example: "Réparation"
                  description: "Catégorie du service"
                nomgroupe:
                  type: string
                  example: "Bâtiment"
                  description: "Groupe du service"
                image:
                  type: string
                  format: binary
                  description: "Image du service"
                description:
                  type: string
                  example: "Service de plomberie professionnel"
                  description: "Description du service"
                prix:
                  type: number
                  example: 25000
                  description: "Prix du service"
      responses:
        201:
          description: Service créé avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Service créé avec succès"
                  service:
                    type: object
                    properties:
                      _id:
                        type: string
                      nomservice:
                        type: string
                      categorie:
                        type: string
                      nomgroupe:
                        type: string
                      image:
                        type: string
        400:
          description: Erreur de validation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Erreur serveur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      summary: Obtenir tous les services
      tags: [Services]
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Numéro de page
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
          description: Nombre de services par page
        - in: query
          name: categorie
          schema:
            type: string
          description: Filtrer par catégorie
        - in: query
          name: nomgroupe
          schema:
            type: string
          description: Filtrer par groupe
      responses:
        200:
          description: Liste des services récupérée avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  services:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                        nomservice:
                          type: string
                        categorie:
                          type: string
                        nomgroupe:
                          type: string
                        image:
                          type: string
                  total:
                    type: integer
                  page:
                    type: integer
                  limit:
                    type: integer
        500:
          description: Erreur serveur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/service/{id}:
    get:
      summary: Obtenir un service par ID
      tags: [Services]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID du service
      responses:
        200:
          description: Service trouvé
          content:
            application/json:
              schema:
                type: object
        404:
          description: Service non trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Mettre à jour un service
      tags: [Services]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID du service
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                nomservice:
                  type: string
                categorie:
                  type: string
                nomgroupe:
                  type: string
                image:
                  type: string
                  format: binary
                description:
                  type: string
                prix:
                  type: number
      responses:
        200:
          description: Service mis à jour avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
        404:
          description: Service non trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Supprimer un service
      tags: [Services]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID du service
      responses:
        200:
          description: Service supprimé avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
        404:
          description: Service non trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
